# Generated by Django 4.2.7 on 2023-11-15 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga', models.PositiveIntegerField()),
                ('jumlah', models.PositiveIntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
